---
title: "Chapter 4"
author: "YC"
date: "January 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter 4

##Question 10

__A__
```{r q10 a}
library(ISLR)
library(MASS)
summary(Weekly)
plot(Weekly)
```

__B__
```{r q10 b}
glm.fit=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,data=Weekly,family=binomial)
summary(glm.fit)
```

__C__
```{r q10 c}
glm.probs=predict(glm.fit,type="response")
glm.pred=rep("Down",length(Weekly$Direction))
glm.pred[glm.probs>0.5]="Up"
table(glm.pred,Weekly$Direction)
mean(glm.pred==Weekly$Direction)
```

__D__
```{r q10 d}
train.yrs=Weekly$Year %in% (1990:2008)
train=Weekly[train.yrs,]
test=Weekly[!train.yrs,]
glm.fit=glm(Direction~Lag2,data=train,family=binomial)
glm.probs=predict(glm.fit,test,type="response")
glm.pred=ifelse(glm.probs>=0.5,"Up","Down")
table(glm.pred,test$Direction)
mean(glm.pred==test$Direction)
```

__E__
```{r q10 e}
lda.fit=lda(Direction~Lag2,data=train)
lda.pred=predict(lda.fit,test)
lda.class=lda.pred$class
table(lda.class,test$Direction)
mean(lda.class==test$Direction)
```

__F__
```{r q10 f}
qda.fit=qda(Direction~Lag2,data=train)
qda.pred=predict(qda.fit,test)
qda.class=qda.pred$class
table(qda.class,test$Direction)
mean(qda.class==test$Direction)
```

__G__
```{r q10 g}
library(class)
set.seed(1)
train.X=as.matrix(train$Lag2)
test.X=as.matrix(test$Lag2)
train.Direction=Weekly$Direction[train.yrs]
knn.pred=knn(train.X,test.X,train.Direction,k=1)
table(knn.pred,test$Direction)
mean(knn.pred==test$Direction)
```

__H__

Logistic regression and LDA produced best fits with 62.5% accuracy of predictions

__I__



##Question 11

__A__
```{r q11 a}
mpg01=as.matrix(ifelse((Auto$mpg)>median(Auto$mpg),1,0))
mpgdf=data.frame(Auto,mpg01)
```

__B__
```{r q11 b}
pairs(mpgdf)
```

__C__
```{r q11 c}
set.seed(1)
train.set=sample(1:nrow(mpgdf),nrow(mpgdf)*0.7,replace=F)
train.data=mpgdf[train.set,]
test.data=mpgdf[-train.set,]
```

__D__
```{r q11 d}
lda.fit11=lda(mpg01~displacement+horsepower+weight+acceleration,data=train.data)
lda.fit11.class=predict(lda.fit11,test.data)$class
table(lda.fit11.class,test.data$mpg01)
mean(lda.fit11.class!=test.data$mpg01)
```

__E__
```{r q11 e}
qda.fit11=qda(mpg01~displacement+horsepower+weight+acceleration,data=train.data)
qda.fit11.class=predict(qda.fit11,test.data)$class
table(qda.fit11.class,test.data$mpg01)
mean(qda.fit11.class!=test.data$mpg01)
```

__F__
```{r q11 f}
glm.fit11=glm(mpg01~displacement+horsepower+weight+acceleration,data=train.data)
glm.fit11.probs=predict(glm.fit11,test.data,type="response")
glm.fit11.probs=ifelse(glm.fit11.probs>0.5,1,0)
table(glm.fit11.probs,test.data$mpg01)
mean(glm.fit11.probs!=test.data$mpg01)
```

__G__
```{r q11 g}
library(class)
knn11.train=cbind(train.data$displacement,train.data$horsepower,train.data$weight,train.data$acceleration)
knn11.test=cbind(test.data$displacement,test.data$horsepower,test.data$weight,test.data$acceleration)
set.seed(1)
knn11.pred=knn(knn11.train,knn11.test,train.data$mpg01,k=1)
table(knn11.pred,test.data$mpg01)
mean(knn11.pred!=test.data$mpg01)
```

##Question 12

__A__
```{r q12 a}
Power=function(){
  print(2^3)
}
Power()
```

__B__
```{r q12 b}
Power2=function(x,a){
  print(x^a)
}
Power2(3,8)
```

__C__
```{r q12 c}
Power2(10,3)
Power2(8,17)
Power2(131,3)
```

__D__
```{r q12 d}
Power3=function(x,a){
  retvalue=(x^a)
  return(retvalue)
}
x=Power3(2,3)
x
```

__E__
```{r q12 e}
x=1:10
plot(x,Power3(x,2),log='xy',xlab='1:10',ylab='x^2')
```

__F__
```{r q12 f}
PlotPower=function(x,a){
  plot(x,x^a)
}
PlotPower(1:10,3)
```